### ISSUE TITLE
No signal 'allocation-changed' on object 'MetaWindowActorX11'

### ISSUE THREAD

**Issue by g0josh** [aunetx/smart-transparent-top-bar#7] opened 2020-10-31 08:24 UTC
Styles work for topbar when installed via browser, but the extensions app reports error - No signal 'allocation-changed' on object 'MetaWindowActorX11' 

After restart the top bar returns to default (not transparent) and the extensions report error.

Pop OS 20.10
GNOME Shell 3.38.1
If it matters I have the following extensions installed and working:
- https://github.com/kazysmaster/gnome-shell-extension-lockkeys
- https://github.com/kgshank/gse-sound-output-device-chooser
- https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

**Comment by g0josh** [comment] 2020-10-31 08:33
Sorry mate, feel free to close if you don't support Gnome 3.38 yet

**Comment by aunetx** [comment] 2021-01-07 22:46
I'm sorry I did not see your issue earlier!

Don't worry, I plan to support gnome 3.38 (and upcoming versions) but I don't have any time to do it right now :(

If you know how to resolve it, feel free to do a PR! But I don't know if my code is readable so that may be hard :/

Anyway, I will try to look at this when I have time (and the other issues btw)

Thanks for the issue! And don't worry, I will not close this until the issue is resolved :)

**Comment by aunetx** [comment] 2021-01-20 12:11
The extension has been ported to 3.38, sorry for the delay... Please tell me if you experience any issue :)

**Closed as completed by aunetx** 2021-01-20 12:11 UTC
Labels: bug
